language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install -n

script:
  - composer test

notifications:
  email: false
  slack:
    rooms:
      secure: AZkmeofTS99q0X6iYHArtYdrw3WnpgkVMTDoYvitxK9S2Q5TH1jjLvYRGzd5ZGpea5CFscaL1NHdBOqm2rO3HJM8LR0AdV6bM9ttCkXJYG52rvCNfCZ7ZXzel50eEMnrb0ookGf3rNWJ7bZDS4L0H56v2YZjHVl6PZoioLcyn5MsLPqNhTwyk1WQ0aRtbolC3EIBKW+Hbs1KbmnHBsYlGlzMwK9O91d5hv+1qJPclCH5SX455XY67oXQFPlZ8R0BJNg6vl3iHf8uXbiLRhecVds2WHCp/Q0hGc8zKCGOxOy6qBEakQ097qoLaL1WXJrp+qSSVerFkyEZ+rmjeo+jf91aoYU3iid+m/jak8Ty/IVdzzLCl4JWy1yYurvmXCIh2Cwii1MXP69Q5obu8ARFj/XqG5lT0RNPcp5otlcRr73pwV7yKNZ2Pw1pNl7t64fzdrZtwQmP3Isnl14P8260O8ELzlwKpIWKWKHc1SoGa5vxUF9Rq4M4TXL2rzTtwMmcVMhQn0ZXZXqEg74NNmh2dIKVAWFMzSphq2boa2FgcvEhaS4ENF86VvmSb7jtaFPmorJDsMh1VrIP33D+1l1ksaHZ2zUxvURzVNB6Oo0sgrLaobpfs2ngLs2RPOaxCMlyd5xKQVRuq7wuhNVWjmOo0pvyN/KppLHIwGkLGDgl+7w=
